name: ecommerce-site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies and Run Tests
      run: npm install && npm test

    - name: Build Docker Image
      # Uses the multi-stage Dockerfile you created
      run: docker build -t reyhenry38/ecommerce-site:latest .

    - name: Log in to Docker Hub
      # Use GitHub Secrets for credentials ($DOCKERHUB_USERNAME, $DOCKERHUB_TOKEN)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
    - name: Push Docker image
      run: docker push reyhenry38/ecommerce-site:latest

    - name: Deploy to Kubernetes
      # This step requires setting up your CI runner with Kubeconfig access
      uses: azure/k8s-set-context@v3
      with:
        # Assuming you store your Kubeconfig as a secret in your CI tool
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
    
    - name: Apply K8s manifest and Restart Deployment
      run: |
        kubectl apply -f app.yaml
        kubectl rollout restart deployment/ecommerce-site
